#! /bin/sh

wmname bspwm

bspc monitor -d                      

bspc config border_width          0
bspc config window_gap            12

bspc config normal_border_color   \#3c4146
bspc config active_border_color   \#3c4146
bspc config focused_border_color  \#398cb7

bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config top_padding           0
bspc config bottom_padding        0
bspc config -m DVI-I-1 left_padding          36 
bspc config -m HDMI-0 left_padding 0

bspc rule -a Virt-manager desktop=\
bspc rule -a Steam desktop=\
bspc rule -a TelegramDesktop desktop=\
bspc rule -a ts3client_linux_amd64 desktop=\
bspc rule -a streamlink-twitch-gui desktop=\

bspc rule -a Plasma monitor=DVI-I-1 state=floating manage=off layer=normal
bspc rule -a plasmashell monitor=DVI-I-1 sticky=on layer=above state=floating 
